/**
 * ✅ EDITABLE FILE - AI Can Modify Values Here
 * 
 * Category Configuration Content
 * This file contains all category definitions for the site
 * 
 * AUTO-GENERATED by Site Builder Template Generator
 * Generated: 2025-12-01T17:12:18.391Z
 */

import type { Category } from './categories.schema'

/**
 * Blog categories with nested subcategories
 * Auto-populated from brand database (BrandCategory table)
 */
export const categories: Category[] = [
  {
    id: "95a38011-aac8-440d-9350-c48d8c6b2fbe",
    name: "Travel By Age",
    slug: "travel-by-age",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "6fdef2ad-03c5-4d39-b053-ff15c8449fc9",
        name: "Babies (0-2)",
        slug: "babies-0-2",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "fd4657f1-8cbf-4737-b5de-339c6af53aed",
        name: "Toddlers (2-4)",
        slug: "toddlers-2-4",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "47300727-9e28-404c-ace1-ddf578423218",
        name: "Little Kids (5-7)",
        slug: "little-kids-5-7",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "650c46ec-e5c8-47d4-a594-5fc8db6b2a8f",
        name: "Big Kids (8-11)",
        slug: "big-kids-8-11",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "ca57c268-04dd-43b3-afe1-498da3826f78",
        name: "Tweens & Teens (12+)",
        slug: "tweens--teens-12",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "6c0eca96-c29a-4354-8f11-d9117f421388",
        name: "Multi-Age/Siblings",
        slug: "multi-agesiblings",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "5af53f22-9257-42d2-a710-3bf36cc1743a",
    name: "Destinations",
    slug: "destinations",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "3e8a89bf-c1e2-49c4-b0fd-71d38f0a67c0",
        name: "North America",
        slug: "north-america",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "1cd1d186-1512-4c24-b768-48949b22636e",
        name: "Central & South America",
        slug: "central--south-america",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "3bb8be97-4ad4-4a7f-8912-146cd6502d32",
        name: "Europe",
        slug: "europe",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "052d5430-2826-494f-bdb6-fde71f168f23",
        name: "Asia",
        slug: "asia",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "1222d609-f367-4432-be53-534ee16a4ede",
        name: "Africa",
        slug: "africa",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "86149c95-0587-46ce-99b2-f4f01dd4a23a",
        name: "Oceania",
        slug: "oceania",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "600a17e5-e5d8-40b2-910e-e35ccfec0f1b",
        name: "Caribbean & Islands",
        slug: "caribbean--islands",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "ce1ae479-53e9-469a-87ca-8d30bef681ad",
    name: "Trip Ideas & Itineraries",
    slug: "trip-ideas--itineraries",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "e3cc0b32-aee7-41fe-ad2b-56ab5018ce48",
        name: "Weekend Getaways",
        slug: "weekend-getaways",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "1d8d724b-3e38-478f-95dd-6937262d909d",
        name: "One-Week Trips",
        slug: "one-week-trips",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "eb8aee92-edaa-4caf-bc70-3861710188e8",
        name: "Two-Week (and Longer) Trips",
        slug: "two-week-and-longer-trips",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "0504c16d-9d96-438d-9664-2556f8f87096",
        name: "Bucket-List Trips with Kids",
        slug: "bucket-list-trips-with-kids",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "e316e07f-2565-4c2d-9fef-720105e98224",
        name: "Seasonal & Holiday Trips",
        slug: "seasonal--holiday-trips",
        showInHeader: true,
        showInFooter: true
      }
    ]
  }
]
