/**
 * ✅ EDITABLE FILE - AI Can Modify Values Here
 * 
 * Site Configuration Content
 * This file contains all customizable values for the site
 * 
 * AUTO-GENERATED by Site Builder Template Generator
 * Brand: The Wandering Fam
 * Generated: 2025-12-01T17:12:18.391Z
 */

import type { SiteConfigSchema, ColorConfigSchema } from './config.schema'

/**
 * Main site configuration
 * Values auto-populated from brand database
 */
export const siteContent: SiteConfigSchema = {
  // Brand identity
  brand: {
    id: "2707c408-c0b4-4710-9c98-af9e0768ec2c",
    name: "The Wandering Fam",
    description: "WanderFam transforms family travel into unforgettable luxury and adventure experiences with expertly curated guides, tips, and stories for every journey.",
    url: "https://thewanderingfam.org",
    logoPath: "/logo.jpg",
    faviconPath: "/logo.jpg",
    ogImagePath: "/logo.jpg",
    mainAppUrl: "https://app.thefaceless.ai"
  },

  // Homepage hero section
  hero: {
    title: "Welcome to The Wandering Fam",
    subtitle: "WanderFam transforms every family trip into a luxurious adventure, offering expertly curated guides, tips, and stories that inspire families to explore the world together in style and comfort."
  },

  // Default author information
  author: {
    name: "The Wandering Fam Team",
    bio: "WanderFam transforms family travel into unforgettable luxury and adventure experiences with expertly curated guides, tips, and stories for every jo...",
    role: "Content Creator",
    image: "/logo.jpg"
  },

  // Section headings throughout the site
  sections: {
    topArticles: {
      title: "Featured Articles",
      description: "Handpicked posts just for you"
    },
    recentPosts: {
      title: "Latest Posts"
    },
    categories: {
      title: "Explore Family Travel and Tourism Topics"
    }
  },

  // Newsletter subscription section
  newsletter: {
    title: "Stay Updated",
    description: "Get the latest from The Wandering Fam delivered to your inbox",
    disclaimer: "Unsubscribe anytime. We respect your privacy."
  },

  // Blog categories (from brand database)
  categories: [
    { 
      name: "Weekend Getaways",
      icon: "FileText",
      slug: "weekend-getaways"
    },
    { 
      name: "Travel By Age",
      icon: "FileText",
      slug: "travel-by-age"
    },
    { 
      name: "North America",
      icon: "FileText",
      slug: "north-america"
    },
    { 
      name: "Babies (0-2)",
      icon: "FileText",
      slug: "babies-0-2"
    },
    { 
      name: "Central & South America",
      icon: "FileText",
      slug: "central--south-america"
    },
    { 
      name: "Destinations",
      icon: "FileText",
      slug: "destinations"
    }
  ],

  // All authors for this brand (with AI-generated portraits)
  authors: [
    {
      id: "f013b3c7-d767-4686-b819-d023b92ae56c",
      name: "Jessica Harper",
      bio: "Jessica combines her passion for adventure with a knack for storytelling, bringing destinations to life through vivid imagery and engaging narratives. With a background in travel journalism and a love for uncovering hidden gems, her writing is both informative and inspiring, guiding families towards creating their own unforgettable journeys.",
      image: "/api/uploads/brands/2707c408-c0b4-4710-9c98-af9e0768ec2c/authors/f013b3c7-d767-4686-b819-d023b92ae56c/portrait-1764608012699.png",
      role: "Family Travel Expert & Adventure Seeker"
    },
    {
      id: "8cb7402b-66a8-4707-af77-1afeea6d9aab",
      name: "Michael Thompson",
      bio: "Michael's writing exudes sophistication and a keen eye for detail, as he reviews luxury accommodations and crafts seamless itineraries for families. His experience in hospitality consulting gives him insider knowledge, allowing him to provide nuanced insights and recommendations that elevate family travel into a lavish experience while maintaining a down-to-earth charm in his prose.",
      image: "/api/uploads/brands/2707c408-c0b4-4710-9c98-af9e0768ec2c/authors/8cb7402b-66a8-4707-af77-1afeea6d9aab/portrait-1764608038418.png",
      role: "Luxury Travel Critic & Family Itinerary Specialist"
    },
    {
      id: "224a59e0-64c8-4488-bd2a-d4d88f10346f",
      name: "Sophia Lin",
      bio: "Sophia's vibrant and energetic writing style is infused with her love for capturing moments through the lens. Her expertise in travel photography and social media trends makes her an invaluable guide for families looking to document their adventures beautifully. Always on the pulse of the latest Instagram-worthy spots, her content is both visually stunning and accessible, encouraging families to create and share their own travel stories.",
      image: "/api/uploads/brands/2707c408-c0b4-4710-9c98-af9e0768ec2c/authors/224a59e0-64c8-4488-bd2a-d4d88f10346f/portrait-1764608081540.png",
      role: "Photography Enthusiast & Social Media Maven"
    }
  ]
}

/**
 * Color configuration
 * Brand colors in oklch() format for consistent rendering
 * Auto-converted from brand hex colors
 */
export const colorContent: ColorConfigSchema = {
  // Light mode colors
  light: {
    primary: "#2563EB",      // #2563EB
    secondary: "#64748B",  // #64748B
    accent: "#F59E0B"         // #F59E0B
  },

  // Dark mode colors (auto-lightened for contrast)
  dark: {
    primary: "#2563EB",
    secondary: "#64748B",
    accent: "#F59E0B"
  }
}
